version: "3.0"

services:
  ######
  # WEB
  vite:
    depends_on:
      - rasa
    build:
      context: .
      dockerfile: dockerfiles/vite.Dockerfile
    container_name: t4b-vite
    volumes:
      - ./vite/src:/usr/src/app/src
      - ./vite/static/img:/usr/src/app/static/img
      - ./script:/usr/src/app/src/handsforchatbots
    networks: ["t4bnet"]
    # links:
    #   - rasa

  webserver:
    depends_on:
      - vite
    image: nginx:1.25.3-alpine
    container_name: t4b-webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "2700:2700" # speech recognition
      - "5055:5055" # rasa actions
      - "5005:5005" # rasa
    volumes:
      - ./vite:/usr/src/app
      - ./nginx:/etc/nginx/conf.d
    networks: ["t4bnet"]
    links:
      - vite
    # environment:
    #   - VOSK_PROXY_PASS="http://t4b-vosk:2700"
    #   - VOSK_UPSTREAM="t4b-vosk:2700"

  rasa:
    build:
      context: .
      dockerfile: ./dockerfiles/rasa.Dockerfile
    container_name: t4b-bot
    networks: ['t4bnet']
    volumes:
      - ./rasa:/app

  action_server:
    build:
      context: .
      dockerfile: ./dockerfiles/rasa-actions.Dockerfile
    container_name: t4b-actions
    platform: linux/x86_64
    networks: ['t4bnet']
    volumes:
      - "./rasa/actions:/app/actions"

  duckling:
    restart: always
    image: rasa/duckling:0.2.0.2-r3
    container_name: t4b-duckling
    platform: linux/x86_64
    networks: ['t4bnet']
    ports:
    - "8000:8000"
    command: ["duckling-example-exe", "-p", "8000", "--no-access-log", "--no-error-log"]

######
# SPEECH RECOGNITION
# vosk:
#   build:
#     context: .
#     dockerfile: dockerfiles/vosk.mac.Dockerfile
#   container_name: t4b-vosk
#   networks: ['t4bnet']

networks: { t4bnet: {} }
